
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 893543
	#The name of the modpack
	modpackName = "Bleeding Edge"
	#The version of the modpack
	modpackVersion = "1.3.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

