
#Party settings
[party]
	#Do parrots party when they're on your shoulder?
	partyShoulder = true
	#Do parrots party when they're flying?
	partyFlying = true
	#Do parrots party when they're standing?
	partyStanding = true
	#Do parrots party when they're sitting?
	partySitting = false
	#Do parrots party when players twerk?
	partyTwerk = false
	#How far do players have to be twerking for parrots to PARTY?!
	#Range: 2.0 ~ 32.0
	partyTwerkRange = 5.0

